#ifndef _MEMORY_PATCHER_IOCTL_H_
#define _MEMORY_PATCHER_IOCTL_H_

#include <ntddk.h>

#define MEMPATCH_DEVICE_NAME       L"\\Device\\MemoryPatcher"
#define MEMPATCH_DOS_DEVICE        L"\\DosDevices\\MemoryPatcher"
#define MEMPATCH_DEVICE_PATH       L"\\\\.\\MemoryPatcher"

#define FILE_DEVICE_MEMPATCH       0x8000
#define MEMPATCH_FUNCTION_READ     0x800
#define MEMPATCH_FUNCTION_WRITE    0x801

#define IOCTL_MEMPATCH_READ  CTL_CODE(FILE_DEVICE_MEMPATCH, MEMPATCH_FUNCTION_READ, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_MEMPATCH_WRITE CTL_CODE(FILE_DEVICE_MEMPATCH, MEMPATCH_FUNCTION_WRITE, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

typedef struct _MEMPATCH_RW_REQUEST {
    ULONG ProcessId;
    ULONGLONG Address;
    ULONG Size;
} MEMPATCH_RW_REQUEST, *PMEMPATCH_RW_REQUEST;

#endif // _MEMORY_PATCHER_IOCTL_H_
